/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import {
  AuthService,
} from './services/auth';
import {
  ConfigService,
} from './services/config';


export namespace Components {

  interface AppExample {}
  interface AppExampleAttributes extends StencilHTMLAttributes {}

  interface AppHome {
    'auth': AuthService;
    'config': ConfigService;
    'viewType': any;
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {
    'auth'?: AuthService;
    'config'?: ConfigService;
    'viewType'?: any;
  }

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface MigrantSkills {}
  interface MigrantSkillsAttributes extends StencilHTMLAttributes {
    'onMigrantSkillsEvent'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppExample': Components.AppExample;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'MigrantSkills': Components.MigrantSkills;
  }

  interface StencilIntrinsicElements {
    'app-example': Components.AppExampleAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'migrant-skills': Components.MigrantSkillsAttributes;
  }


  interface HTMLAppExampleElement extends Components.AppExample, HTMLStencilElement {}
  var HTMLAppExampleElement: {
    prototype: HTMLAppExampleElement;
    new (): HTMLAppExampleElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMigrantSkillsElement extends Components.MigrantSkills, HTMLStencilElement {}
  var HTMLMigrantSkillsElement: {
    prototype: HTMLMigrantSkillsElement;
    new (): HTMLMigrantSkillsElement;
  };

  interface HTMLElementTagNameMap {
    'app-example': HTMLAppExampleElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'migrant-skills': HTMLMigrantSkillsElement
  }

  interface ElementTagNameMap {
    'app-example': HTMLAppExampleElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'migrant-skills': HTMLMigrantSkillsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
